- hosts: pi
  become: yes
  vars:
    home: /home/admin
    
  tasks:

  - name: create admin user
    user:
      name: admin
      home: "{{ home }}"
      password: $6$OjRCvbjSZAF2J$TNkm/B6HCjr1PArGd7OTILT/0JZzTkTxq6ob6tKO6b1qLuKHyPFfvh4pslJ7eMXqwkewMTaU6MNBm2tiHIxdc.
      shell: /bin/bash

  - name: install required apt packages
    shell: apt-get install -y emacs-nox htop python python-pandas python-numpy ipython python-dbus python-pip python-setuptools python-dev python-gobject expect musl zip samba samba-common-bin

  - name: install pip packages
    shell: pip install pyserial paho-mqtt pytest gpxpy

  - name: prepare musl for ldd of edg cython so compiled from armhf/arm32v6 alpine to load correctly
    shell: cd /lib && ln -sf ld-musl-armhf.so.1 libc.musl-armhf.so.1
