- hosts: pi
  become: yes
  vars:
    home: /home/admin
    
  tasks:

  - name: Format /dev/mmcblk0p2 to ext4
    filesystem:
      fstype: ext4
      dev: /dev/mmcblk0p2

  - name: Format /dev/mmcblk0p3 to ext4
    filesystem:
      fstype: ext4
      dev: /dev/mmcblk0p3

  - name: mount mmcblk0p2 to /config (you must create in gparted first)
    mount:
      path: /config
      src: /dev/mmcblk0p2
      fstype: ext4
      state: mounted

  - name: mount mmcblk0p3 to /data (you must create in gparted first)
    mount:
      path: /data
      src: /dev/mmcblk0p3
      fstype: ext4
      state: mounted

  - name: install ecodroidgps pip packages
    pip:
      requirements: "{{ home }}/ecodroidgps/requirements.txt"

  - name: prepare bluetooth folder link in mounted dev to store pairing info
    shell: mkdir -p /config/bluetooth && rm -rf /var/lib/bluetooth && ln -sf /config/bluetooth /var/lib/bluetooth

  - name: install ecodroidgps service
    shell: cd "{{ home }}/ecodroidgps" && ./install_service.sh

  - lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Storage='
      line: 'Storage=volatile'

  - shell: sudo systemctl disable rsyslog ; sudo systemctl stop rsyslog ; echo done
