- hosts: pi
  become: yes
  vars:
    home: /home/edl
    
  tasks:

  - name: update, upgrade
    shell: apt-get update &&  apt-get -y upgrade
  
  - name: install apt packages
    shell:  apt-get install -y bluez git bc libusb-dev libdbus-1-dev libglib2.0-dev libudev-dev libical-dev libreadline-dev emacs

  - lineinfile:
      path:  /etc/bluetooth/main.conf
      regexp: '^(#Name =|Name =)'
      line: Name = EcoDroidGPS Bluetooth GPS

  # positioning;misc from http://bluetooth-pentest.narod.ru/software/bluetooth_class_of_device-service_generator.html
  - lineinfile:
      path:  /etc/bluetooth/main.conf
      regexp: '^(##Class =|#Class =)'
      line: Class = 0x10000

  - name: check bluetooth service active
    shell: systemctl is-active bluetooth

  - name: bluetoothd ver check
    shell: bluetoothd -v | grep 5.50
    args:
      executable: /bin/bash

  - name: bluetoothctl ver check
    shell: bluetoothctl -v | grep 5.50
    args:
      executable: /bin/bash

  - name: btmgmt check device present
    shell: btmgmt info | grep addr | grep class
    args:
      executable: /bin/bash

