- hosts: pi
  become: yes
  vars:
    home: /home/admin
    
  tasks:

  - name: create admin user
    user:
      name: admin
      home: "{{ home }}"
      password: $6$OjRCvbjSZAF2J$TNkm/B6HCjr1PArGd7OTILT/0JZzTkTxq6ob6tKO6b1qLuKHyPFfvh4pslJ7eMXqwkewMTaU6MNBm2tiHIxdc.
      shell: /bin/bash

  - name: make admin sudo without passwd
    lineinfile:
      path: /etc/sudoers
      regexp: '^admin ALL=(ALL) ALL'
      line: 'admin ALL=(ALL) NOPASSWD: ALL'

  - name: Disable SSH root login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'

  - name: Disable strict host checking in ssh config
    blockinfile:
      path: /home/admin/.ssh/config
      create: yes
      mode: 0600
      owner: admin
      group: admin
      block: |
        Host *
          StrictHostKeyChecking no

  - name: set hostname
    shell: echo ecodroidgps > /etc/hostname    	  

  - name: restart ssh
    service:
      name: ssh
      state: restarted

  - name: install packages
    apt:
      name: emacs-nox, htop, python3, ipython3, python3-pip, python3-pandas, python3-dbus, python3-setuptools, python3-dev, expect, zip, samba, samba-common-bin, dos2unix, libxml2-utils, libnss-mdns
      state: present
 
  - name: copy smb.conf
    copy:
      src: smb.conf
      dest: /etc/samba/smb.conf
      
  - name: restart samba
    service:
      name: smbd
      state: restarted


