- hosts: pi
  become: yes
  vars:
    home: /home/admin
    
  tasks:

  - name: ensure mount point dirs exist - 'pytest' in ecodroidgps dir would mount /data
    shell: mkdir -p /data

  - name: test ecodroidgps
    shell: cd "{{ home }}/ecodroidgps" && pytest

  - name: prepare bluetooth folder link in mounted dev to store pairing info
    shell: mkdir -p /config/bluetooth && rm -rf /var/lib/bluetooth && ln -s /config/bluetooth /var/lib/bluetooth

  - name: install ecodroidgps service
    shell: cd "{{ home }}/ecodroidgps" && ./install_service.sh

  - lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Storage='
      line: 'Storage=volatile'
