- hosts: pi
  become: yes
  become_user: admin
  
  vars:
    home: /home/admin
    
  tasks:

  - name: install/update bluez-compassion
    git:
      repo: 'https://github.com/ykasidit/bluez-compassion.git'
      dest: "{{ home }}/bluez-compassion"
      clone: yes
      update: yes

  - name: install ecodroidgps
    git:
      repo: https://github.com/ykasidit/ecodroidgps.git
      dest: "{{ home }}/ecodroidgps"
      clone: yes
      update: yes
