- hosts: pi
  become: yes
    
  tasks:

  - name: mod mosquitto conf
    shell: sudo sed -i "s/persistence true/persistence false/g" /etc/mosquitto/mosquitto.conf ; systemctl enable mosquitto && systemctl start mosquitto

  - lineinfile:
      path: /etc/mosquitto/mosquitto.conf
      regexp: '^persistence'
      line: 'persistence false'

  - lineinfile:
      path: /etc/mosquitto/mosquitto.conf
      regexp: '^log_dest'
      line: 'log_dest none'

  - name: check mosquitto conf
    shell: grep "persistence false" /etc/mosquitto/mosquitto.conf

  - name: restart mosquitto
    shell: systemctl restart mosquitto

  - name: check mosquitto running
    shell: systemctl is-active mosquitto


 
