- hosts: pi
  become: yes
  vars:
    home: /home/admin
    bluez_url: http://www.kernel.org/pub/linux/bluetooth/bluez-5.50.tar.xz
    bluez_target_dir: "{{ home }}/bluez-5.50"
    
  tasks:

  - shell: mkdir -p /etc/systemd/system/networking.service.d

  - name: copy reduce-timeout.conf
    copy:
      src: reduce-timeout.conf
      dest: /etc/systemd/system/networking.service.d/reduce-timeout.conf

  - apt_repository:
      repo: deb http://httpredir.debian.org/debian sid main contrib non-free
      state: present

  - name: make sure bluez apt package removed
    shell: sudo apt-get purge bluez

  - name: install apt packages
    shell: sudo apt-get install -y git bc libusb-dev libdbus-1-dev libglib2.0-dev libudev-dev libical-dev libreadline-dev autoconf emacs-nox htop python python-pandas python-numpy ipython python-dbus python-pip python-setuptools python-dev mosquitto mosquitto-clients python-gobject

  - name: install pip packages
    shell: sudo pip install nose2 pyserial paho-mqtt

  - name: mod mosquitto conf
    shell: sudo sed -i "s/persistence true/persistence false/g" /etc/mosquitto/mosquitto.conf ; systemctl enable mosquitto && systemctl start mosquitto

  - name: check mosquitto conf
    shell: grep "persistence false" /etc/mosquitto/mosquitto.conf

  - name: mkdir bluez_target_dir
    file:
      path: "{{ bluez_target_dir }}"
      state: directory
    
  - name: download and extract bluez src    
    unarchive:
      src: "{{ bluez_url }}"
      dest: "{{ home }}"
      remote_src: yes

  - name: bluez configure make make install
    shell: "cd {{ bluez_target_dir }} && ./configure --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var && make && sudo make install"
    args:
      executable: /bin/bash

  - name: bluetoothctl enable and start
    shell: systemctl daemon-reload && systemctl enable bluetooth && systemctl start bluetooth

  - name: bluetoothctl ver check
    shell: bluetoothctl -v | grep 5.50
    args:
      executable: /bin/bash

  

    
    
