- hosts: pi
  become: yes
  vars:
    home: /home/admin
    
  tasks:

  - name: ensure mount point dirs exist - test ecodroidgps would mount
    shell: mkdir -p /config ; mkdir -p /data

  - name: test ecodroidgps
    shell: cd "{{ home }}/ecodroidgps" && nose2 -F --quiet

  - name: prepare bluetooth folder link in mounted dev to store pairing info
    shell: mkdir -p /config/bluetooth && rm -rf /var/lib/bluetooth && ln -s /config/bluetooth /var/lib/bluetooth

  - name: install ecodroidgps service
    shell: cd "{{ home }}/ecodroidgps" && ./install_service.sh

  - lineinfile:
      path: /etc/systemd/journald.conf
      regexp: '^Storage='
      line: 'Storage=volatile'

  - name: copy cfg80211 conf
    copy:
      src: cfg80211.conf
      dest: /etc/modprobe.d/cfg80211.conf
      
  - name: copy mac80211 conf
    copy:
      src: mac80211.conf
      dest: /etc/modprobe.d/mac80211.conf

  - name: copy xradio_wlan conf
    copy:
      src: xradio_wlan.conf
      dest: /etc/modprobe.d/xradio_wlan.conf


  - shell: depmod -ae ; update-initramfs -u

  - lineinfile:
      path: /etc/overlayroot.conf
      regexp: '^overlayroot='
      line: 'overlayroot="tmpfs"'

