- hosts: pi
  become: no
  vars:
    home: /home/admin
    
  tasks:

  - name: install/update bluez-compassion
    git:
      repo: 'https://github.com/ykasidit/bluez-compassion.git'
      dest: "{{ home }}/bluez-compassion"
      clone: yes
      update: yes

  - name: install/update bluez-gatt-server
    git:
      repo: 'https://github.com/ykasidit/bluez-gatt-server.git'
      dest: "{{ home }}/bluez-gatt-server"
      clone: yes
      update: yes

  - name: test bluez-gatt-server
    shell: cd "{{ home }}/bluez-gatt-server" && nose2

  - name: install micropygps
    git:
      repo: https://github.com/ykasidit/micropyGPS-python2.git
      dest: "{{ home }}/micropyGPS-python2"
      clone: yes
      update: yes

  - name: install ecodroidgps
    git:
      repo: https://gitlab.com/ykasidit/ecodroidgps_bin.git
      dest: "{{ home }}/ecodroidgps"
      clone: yes
      update: yes

  - name: ensure mount point dirs exist
    shell: mkdir -p /config ; mkdir -p /data

  - pip:
      name: pyserial

  - name: test ecodroidgps
    shell: cd "{{ home }}/ecodroidgps" && nose2 -F


