- hosts: pi
  become: yes
  vars:
    home: /home/admin
    bluez_url: http://www.kernel.org/pub/linux/bluetooth/bluez-5.50.tar.xz
    bluez_target_dir: "{{ home }}/bluez-5.50"
    
  tasks:

  - name: dl miniconda
    get_url:
      url: https://repo.continuum.io/miniconda/Miniconda-latest-Linux-armv7l.sh
      dest: "{{  home  }}/miniconda.sh"

  - name: install miniconda
    command: bash -c "ls /home/admin/miniconda && echo 'already installed' || (chmod +x {{ home }}/miniconda.sh && {{ home }}/miniconda.sh -b -p {{ home }}/miniconda)"

  - name: admin bashrc add miniconda
    command: bash -c "grep miniconda /home/admin/.bashrc && echo 'already done' || (echo 'export PATH=\"/home/admin/miniconda/bin:$PATH\"' >> /home/admin/.bashrc)"

  - command: bash -c "rm /usr/bin/conda ; ln -s /home/admin/miniconda/bin/conda /usr/bin/conda"
  
  - name: admin install rpi pandas
    become_user: admin
    shell: conda list | grep pandas && echo 'pandas already installed' || (sudo conda install -c rpi pandas -y)
    args:
      executable: /bin/bash

  - name: install software packages
    command: sudo apt-get install -y git bc libusb-dev libdbus-1-dev libglib2.0-dev libudev-dev libical-dev libreadline-dev autoconf emacs-nox htop

  - name: mkdir bluez_target_dir
    file:
      path: "{{ bluez_target_dir }}"
      state: directory
    
  - name: download and extract bluez src    
    unarchive:
      src: "{{ bluez_url }}"
      dest: "{{ home }}"
      remote_src: yes

  - name: bluez configure make make install
    shell: "cd {{ bluez_target_dir }} && ./configure --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --localstatedir=/var && make && sudo make install"
    args:
      executable: /bin/bash

  - name: bluez service check
    shell: grep '/usr/libexec/bluetooth' /lib/systemd/system/bluetooth.service && systemctl daemon-reload && systemctl enable bluetooth && systemctl start bluetooth
    args:
      executable: /bin/bash



  - name: install/update bluez-compassion
    git:
      repo: 'https://github.com/ykasidit/bluez-compassion.git'
      dest: "{{ home }}/bluez-compassion"
      clone: yes
      update: yes

  - name: install/update bluez-gatt-server
    git:
      repo: 'https://github.com/ykasidit/bluez-gatt-server.git'
      dest: "{{ home }}/bluez-gatt-server"
      clone: yes
      update: yes


    
    
