version: "3.5"
services:


  debarm:
    build: debarm
    image: debarm:latest
    container_name: debarm
    volumes:
      - /data/docker_armhf_debian_sid:/ -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
      - /data/debootstrap-armhf/root:/root
